M48
; DRILL file KiCad 10.0.0 date 2026-04-03T01:28:24
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-04-03T01:28:24-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.0
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.000
%
G90
G05
T1
X221.353Y-161.696
X227.133Y-161.696
T2
X238.426Y-108.61
X238.426Y-120.04
M30
